Minimal execution time and display on hover
deshaw/jupyterlab-execute-time pull request #17
Opened 2020-11-01 15:28 UTC by toonijn

This PR adds two features, requested in #12 .
- Make it possible to only display the execution time on hover
![Selection_036](https://user-images.githubusercontent.com/9020072/97806951-67dd6c00-1c5e-11eb-8d4a-c8d94af20faf.png)
- Only report execution time when a certain minimal runtime has been exceeded
![Selection_039](https://user-images.githubusercontent.com/9020072/97807024-cdc9f380-1c5e-11eb-9e26-b9d2b6e32d07.png)

For this one new setting (`minimal_time`) was added and a new option for `positioning` (`hover`) is available.
![Selection_040](https://user-images.githubusercontent.com/9020072/97807083-200b1480-1c5f-11eb-85e6-cb04cb8621ee.png)

2020-11-04 00:29 UTC, mlucool requested changes
Thanks again for your great contribution!

I'd prefer we keep each PR to one idea. Let's focus this one on hover, which we are happy to accept as a feature. The code here looks mostly good, but the hover position I'm a bit uneasy about. If you have a long line (e.g. `print('abcd'*50)` on my screen), it occludes the text when you to to interact with it. It's also a bit distracting for me as it keeps changing which cells it appears on as I switch which cell I am working on. Was it possible to show this data only over hover in the gutter to the left of cell (e.g. as a tooltip)?

W.r.t the `minimal_time` feature, I am not sure that is a good fit for this plugin, at least as designed. @Elind77 commented that there is no real absolute number and it may vary per notebook. Do you have any use cases for this?

2020-11-13 15:33 UTC, toonijn commented
- You're right. I've removed the minimal_time. (It is indeed hard to give a general minimal time. But the use-case I was thinking of is to remove clutter. Let's say if the execution time is less than 10ms or something, in no language would this be an interesting time. I'm not very convinced about this feature either. So I'll just remove it.)
- I agree, at the moment the hover-position is quite distracting. But it was the best I found. I'm hesitant to prefer a tooltip, because that would easily clash with the style of the page. I've found no other tooltips in jupyterlab, so I don't really like to introduce the first one.

I'll try to only show the time when the mouse hovers over the code cell. In that way it may be less distracting, and it will no longer occlude long output lines (when the mouse is moved).

2020-11-18 14:36 UTC, mlucool commented
Thanks @toonijn, please let me know when to re-review

2021-01-04 08:51 UTC, toonijn commented
I'm sorry it took me a long time to get back to you.

This is my proposal:
![Selection_107](https://user-images.githubusercontent.com/9020072/103516789-618f8a00-4e71-11eb-84c0-5d88db9d8b58.png)

Only when the mouse hovers over the code the time will be shown. I've used it for some weeks and mixed feelings: it is not bothersome or annoying, but I also don't see any improvement over the default visibility. I guess this is more of a personal opinion and maybe there are people who like the more 'visual-compact' look, as suggested in #12 .

@mlucool In code it is a very minor thing, but I think it answers your previous remarks.

2021-01-11 21:45 UTC, mlucool commented
Thanks for your continued efforts. I'll review this soon

2021-01-12 20:35 UTC, mlucool commented
Thanks again for your contribution. I played with it and it seems to work well.

2021-01-12 20:35 UTC, merged

2021-01-18 14:17 UTC, mlucool commented
This has been published as 1.1.0